blueprint:
  name: High Humidity Monitor
  description: >
    💧 High Humidity Monitor  
    This blueprint checks all humidity sensors every hour and sends notifications if the humidity of any sensor exceeds a configured threshold. Optionally, it can perform custom actions.
  domain: automation
  input:
    humidity_threshold:
      name: Humidity Threshold
      description: >
        Notifications are sent if the humidity exceeds this value.
      default: 70
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    notification_title:
      name: Notification Title
      description: >
        Title for the notification.
      default: "High Humidity Detected"
      selector:
        text:
    notification_message:
      name: Notification Message
      description: >
        Message for the notification.
      default: "One or more areas in your home have high humidity levels."
      selector:
        text:
    notify_target:
      name: Notification Target (Optional)
      description: >
        Select devices or services to receive the notification. If left empty, no notification will be sent.
      selector:
        target:
    custom_actions:
      name: Custom Actions (Optional)
      description: >
        Specify additional actions to execute when humidity exceeds the threshold.
      selector:
        action:

trigger:
  - platform: time
    at: "00:00"

condition:
  - condition: template
    value_template: >
      {% set high_humidity = states.sensor | selectattr('attributes.device_class', 'eq', 'humidity') | selectattr('state', 'defined') | selectattr('state', '>', !input humidity_threshold | float) | list %}
      {{ high_humidity | length > 0 }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set high_humidity = states.sensor | selectattr('attributes.device_class', 'eq', 'humidity') | selectattr('state', 'defined') | selectattr('state', '>', !input humidity_threshold | float) | list %}
              {{ high_humidity | length > 0 }}
        sequence:
          - service: notify
            target: !input notify_target
            data:
              title: !input notification_title
              message: >
                {% set high_humidity = states.sensor | selectattr('attributes.device_class', 'eq', 'humidity') | selectattr('state', 'defined') | selectattr('state', '>', !input humidity_threshold | float) | list %}
                High humidity detected for sensors: 
                {{ high_humidity | map(attribute='name') | join(', ') }}
  - sequence: !input custom_actions