blueprint:
  name: High Humidity Notifications & Actions
  description: >
    # 💧 High Humidity Notifications & Actions

    Monitors all humidity sensors and sends notifications or runs actions when a threshold is exceeded.

    - Supports time-based trigger.
    - Allows excluding specific humidity sensors.
    - Sends notifications to selected mobile devices.
    - Supports optional custom actions.

  domain: automation

  input:
    include_time:
      name: Use Time Trigger
      description: Enable or disable the time trigger
      default: time_enabled
      selector:
        select:
          options:
            - label: Enable time trigger
              value: time_enabled
            - label: Disable time trigger
              value: time_disabled

    time:
      name: Time
      description: Time of day to run the automation (if enabled)
      default: '10:00:00'
      selector:
        time:

    weekday_options:
      name: Days of Week
      description: Days to run the automation
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          mode: list
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

    threshold:
      name: Humidity Threshold (%)
      description: Alert when humidity exceeds this percentage
      default: 65
      selector:
        number:
          min: 5
          max: 100
          step: 1
          unit_of_measurement: '%'

    exclude_sensors:
      name: Excluded Humidity Sensors
      description: Sensors to exclude from monitoring
      default: []
      selector:
        target:
          entity:
            domain: sensor
            device_class: humidity
            multiple: true

    notify_device:
      name: Devices to Notify
      description: Mobile devices to send notifications to
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    notify_title:
      name: Notification Title
      description: Title of the notification message
      default: High Humidity Alert
      selector:
        text:

    notify_message:
      name: Notification Message
      description: Message content; use {{sensors}} to include sensor list
      default: High humidity detected in: {{sensors}}
      selector:
        text:

    actions:
      name: Actions to Execute
      description: Optional actions to run when humidity is high
      default: []
      selector:
        action: {}

variables:
  threshold: !input threshold
  exclude_sensors: !input exclude_sensors
  days: !input weekday_options
  sensors: >
    {% set ns = namespace(list=[]) %}
    {% for s in states.sensor | selectattr('attributes.device_class', 'eq', 'humidity') %}
      {% if s.entity_id not in exclude_sensors and s.state | float(-1) > threshold %}
        {% set ns.list = ns.list + [s.name ~ ' (' ~ s.state ~ '%)'] %}
      {% endif %}
    {% endfor %}
    {{ ns.list }}

trigger:
  - platform: time
    at: !input time

condition:
  - condition: template
    value_template: "{{ sensors | length > 0 }}"
  - condition: template
    value_template: "{{ now().strftime('%a').lower()[:3] in days }}"

action:
  - service: notify.mobile_app
    data:
      target: !input notify_device
      title: !input notify_title
      message: >
        {{ !input notify_message | replace('{{sensors}}', sensors) }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ actions | length > 0 }}"
        sequence: !input actions

mode: single
